export const DATETIME_CONSTANT = Object.freeze({
    DD_MM_YYYY_SLASH: 'DD/MM/YYYY',
    DD_MMM_YYYY_SLASH: 'DD/MMM/YYYY',
    DD_MMMM_YYYY_SLASH: 'DD/MMMM/YYYY',
    DD_MM_YYYY_DASH: 'DD-MM-YYYY',
    DD_MMM_YYYY_DASH: 'DD-MMM-YYYY',
    DD_MMMM_YYYY_DASH: 'DD-MMMM-YYYY',
});